### ISSUE TITLE
How to integrate with `aws-xray-sdk`?

### ISSUE THREAD

**Issue by williamrjribeiro** [Qvalia/knex-aws-data-api#3]
Hello 🧇 

I'm trying to integrate `aws-xray-sdk` into my application. How can I provide an instrumented version of `RDSDataClient` to `knex` that uses the `postgres` client from `@qvalia/knex-aws-data-api`?

 My app uses the following dependencies:

```
"@aws-sdk/client-rds-data": "^3.621.0",
"@qvalia/knex-aws-data-api": "^1.0.1",
"knex": "^3.1.0",
```

Thanks!

**Comment by QAnders** [comment]
Sorry for the late reply!

The `knex-aws-data-api` is solely for usage through the Data-API using AWS Aurora Serverless v1 or v2. If you need a native Postgresql client then use the regular `knex` package.
So, what I am trying to say here is that we are not using a "connected" Postgres client in the module. The PG client is only used to create SQL statements that we then execute through the Data-API.
